[project]
name = "openeo_xarray_executor"
version = "2025.5.1"
description = "dependencies for openeo processes dask + openeo processes dask ml"
authors = [{ name = "Peter Zellner", email = "peter.zellner@dlr.de" }]
requires-python = ">=3.14,<3.15"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "dask-gateway>=2024.1.0,<2025",
    "openeo-pg-parser-networkx>=2024.4.0",
    "pystac-client>=0.8.2,<1",
    "click>=8.1.7",
    "pydantic>=2.7.0,<3",
    "odc-stac>=0.3.3,<1",
    "stactools>=0.4.8,<0.5",
    "rioxarray>=0.15.1,<1",
    "netCDF4>=1.7.3",
#    "netCDF4<=1.6.5", <-old version
    "openeo-processes-dask-ml[torch-cpu, scikit-learn]",
    "gdal==3.13.1",
    "ml-datacube-bridge",
]

[project.scripts]
openeo_executor = "openeo_xarray_executor.cli:cli"

[dependency-groups]
dev = [
    "pytest>=7.2.0,<8",
    "ipykernel>=6.15.1,<7",
    "pre-commit>=2.20.0,<3",
    "pytest-cov>=4.0.0,<5",
    "pytest-asyncio>=0.23.0,<0.24",
    "pydoc-markdown==4.8.2",
]

[tool.uv]
default-groups = ["dev"]

[tool.uv.sources]
openeo-processes-dask-ml = { git = "https://github.com/Open-EO/openeo-processes-dask-ml.git" }
torch = { index = "pytorch-cpu" }
#ml-datacube-bridge = { git = "https://github.com/Open-EO/openeo-processes-dask-ml.git", subdirectory = "ml_datacube_bridge" }

[tool.uv.build-backend]
module-name = ["openeo_xarray_executor"]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

# --- CPU ---
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true